
-- PPAS와 호환되게 NOW() 함수를 추가함.
-- SYNONYM이 적용되지 않아 모든 USER에 신규등록함. BIZOWN, BIZAPP, BIZBAT
CREATE or Replace FUNCTION BIZOWN.NOW 
RETURN DATE
AS
    SQL_STR VARCHAR(1000);
    TRN_DATE DATE;
BEGIN
    SQL_STR := 'Select sysdate from dual';
    execute IMMEDIATE SQL_STR into TRN_DATE;
    RETURN TRN_DATE;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

GRANT EXECUTE ON BIZOWN.NOW TO BIZAPP;
GRANT EXECUTE ON BIZOWN.NOW TO BIZBAT;



-- PostgreSQL Role: bizown
-- DROP ROLE bizown;
CREATE ROLE bizown LOGIN
  ENCRYPTED PASSWORD 'md52db927202e507311c83ca4c6e4c6aeff'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
 ALTER ROLE bizown  SET search_path = bizdb, bizsh, public;
COMMENT ON ROLE bizown IS 'BizNaru.SchemaOwner(bizown123!)';


-- DROP ROLE bizapp;
CREATE ROLE bizapp LOGIN
  ENCRYPTED PASSWORD 'md580f877e3bd93e19dc84f6e0128844347'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
 ALTER ROLE bizapp SET search_path = bizdb, bizsh;
COMMENT ON ROLE bizapp IS 'BizNaru.ApplicationUser(bizapp123!)';

