(SELECT
'합계' AS BILL_TGT_YM
,'' AS BM_CD_NM
,'' AS SVC_CONT_ID
,'' AS PROD_NM
,'' AS NFL_CUST_CPNM_NM
,'' AS SVC_CONT_ASSET_1_IDFY_VAL
,'' AS SERVICE_DATE
,'' AS LAST_SVC_CONT_STTUS_CD_NM
,SUM(total_bill) AS total_bill
,SUM(FOREC_PENLT_AMT) AS FOREC_PENLT_AMT
,'' AS CONT_PURP_NM
,'' AS WRK_STTUS_CD
,'' AS WRK_STTUS_NM
,'' AS BILL_TRT_RESLT_NM
,'' AS PARAM_SBST
,'' AS SALE_PARTY_ID
,'' AS SALE_PARTY_NM
,'' AS DEPT_NM
,'' AS DEPT_CD
,'' AS CUST_NM
,'' AS BILL_ACC_ID
,'' AS INT_LINE_DIV_NM
,'' AS CHAGE_ADJ_STTUS_CD
,'' AS DESC_SBST
,'' AS CHAGE_ADJ_STTUS_NM
,'' AS RQTR_NM
,'' AS REVIWR_NM
,'' AS PRMTN_COUNT
FROM (
SELECT * FROM (
SELECT 
 ROUND((nvl(A.TMON_BILL_AMT,0) - nvl(A.TMON_DC_AMT, 0) + nvl(A.TMON_ADJ_AMT, 0))) as total_bill
, ROUND(nvl(A.EXPT_PENLT, 0)) as FOREC_PENLT_AMT
FROM BL_BILL_ACC_BILL_TXN A
JOIN AC_SVC_CONT_BAS B
ON A.SVC_CONT_ID = B.SVC_CONT_ID
JOIN MB_CUST_BAS N
ON B.NFL_CUST_ID = N.CUST_ID 
JOIN CW_COMN_CD_BAS F
ON B.BM_CTG_CD = F.CD_ID
AND F.CD_GROUP_ID = '70044'
AND F.EXPNSN_STR_VAL_1 = '01'
AND F.EFCT_FNS_DT = TO_DATE('99991231', 'YYYYMMDD')
JOIN AC_SVC_CONT_PROD_DTL C
    ON A.SVC_CONT_ID = C.SVC_CONT_ID
    AND C.LAST_SVC_CONT_PROD_STTUS_CD NOT IN ('C')
JOIN PR_PROD_BAS D
    ON C.PROD_ID = D.PROD_ID
    AND D.PROD_TYPE_CD = 'P'
    AND D.PROD_EFCT_FNS_DT = TO_DATE('99991231', 'YYYYMMDD')

LEFT JOIN MB_SALE_PARTY_BAS M
ON A.SVC_CONT_ID = M.SVC_CONT_ID
AND SALE_PARTY_DIV_CD = 'S'
LEFT JOIN AC_SVC_CONT_BILL_REL_HST O
ON B.SVC_CONT_ID = O.SVC_CONT_ID
AND O.EFCT_FNS_DT = TO_DATE('99991231000000', 'YYYYMMDDHH24MISS')
LEFT JOIN MB_CUST_ACC_BAS Q
ON N.CUST_ID = Q.CUST_ID
AND Q.ACC_TYPE_CD='1001'
AND Q.ACC_STTUS_CD='1002'
 
LEFT JOIN (SELECT B.SVC_CONT_ID, B.BILL_TGT_YM, MAX(B.RQTR_ID) AS RQTR_ID, MAX(REVIWR_ID) AS REVIWR_ID, MAX(B.CHAGE_ADJ_STTUS_CD) AS CHAGE_ADJ_STTUS_CD,  MAX(B.DESC_SBST) AS DESC_SBST   FROM
                        (SELECT SVC_CONT_ID, BILL_TGT_YM,  MAX(STTUS_CHG_DT) as STTUS_CHG_DT FROM BL_CHAGE_ADJ_RQT_TXN 
                        WHERE 1=1 
                         
						   AND BILL_TGT_YM   >=   201801
						 
						 
						   AND BILL_TGT_YM   <=   201812
						 				 
                        GROUP BY SVC_CONT_ID, BILL_TGT_YM
                        ) A  
                        JOIN BL_CHAGE_ADJ_RQT_TXN B
                        ON A.SVC_CONT_ID = B.SVC_CONT_ID 
                        AND A.BILL_TGT_YM = B.BILL_TGT_YM
                        AND A.STTUS_CHG_DT = B.STTUS_CHG_DT
                        group by B.SVC_CONT_ID, B.BILL_TGT_YM
) S
ON S.SVC_CONT_ID = A.SVC_CONT_ID
AND S.BILL_TGT_YM = A.BILL_TGT_YM
	WHERE 1=1  
   AND A.BILL_TGT_YM   >=   201801 
   AND A.BILL_TGT_YM   <=   201812

 
)
WHERE 1=1
))

UNION ALL

 (select  
TMP1.BILL_TGT_YM
, TMP1.BM_CD_NM
, TMP1.SVC_CONT_ID
, TMP1.PROD_NM
, TMP1.NFL_CUST_CPNM_NM
, E.SVC_CONT_ASSET_1_IDFY_VAL
, TO_CHAR(TMP1.SVC_CONT_SBSC_DT,'yyyy-mm-dd')  as SERVICE_DATE
, G.CD_NM LAST_SVC_CONT_STTUS_CD_NM
, ROUND((nvl(TMP1.TMON_BILL_AMT,0) - nvl(TMP1.TMON_DC_AMT, 0) + nvl(TMP1.TMON_ADJ_AMT, 0))) as total_bill
, ROUND(nvl(TMP1.EXPT_PENLT, 0)) as FOREC_PENLT_AMT
, I.CD_NM as CONT_PURP_NM
, J.WRK_STTUS_CD
, K.CD_NM AS WRK_STTUS_NM
, L.CD_NM AS BILL_TRT_RESLT_NM
, TMP1.PARAM_SBST
, TMP1.SALE_PARTY_ID
, TMP1.SALE_PARTY_NM
, TMP1.DEPT_NM
, TMP1.DEPT_CD
, TMP1.CUST_NM
, TMP1.BILL_ACC_ID
, P.CD_NM AS INT_LINE_DIV_NM
, TMP1.CHAGE_ADJ_STTUS_CD
, TMP1.DESC_SBST
, T.CD_NM AS CHAGE_ADJ_STTUS_NM
, (SELECT USER_NM FROM MB_USER_BAS WHERE USER_ID = TMP1.RQTR_ID) AS RQTR_NM
, (SELECT USER_NM FROM MB_USER_BAS WHERE USER_ID = TMP1.REVIWR_ID) AS REVIWR_NM
, ADAT.PRMTN_COUNT
from (
    SELECT * FROM (
    SELECT 
    A.BILL_TGT_YM
    , F.CD_NM AS BM_CD_NM
    , A.SVC_CONT_ID
    , B.NFL_CUST_CPNM_NM
    , B.SVC_CONT_SBSC_DT
    , A.TMON_BILL_AMT
    , A.TMON_DC_AMT
    , A.TMON_ADJ_AMT
    , A.EXPT_PENLT
    , A.PARAM_SBST
    , N.CUST_NM
    , B.LAST_SVC_CONT_STTUS_CD
    , B.CONT_PURP_CD
    , A.BILL_TRT_RESLT_CD
    , B.INET_CIRCUIT_DIV_CD
    , N.CUST_ID
    , M.SALE_PARTY_ID
    , M.SALE_PARTY_NM
    , M.DEPT_NM
    , M.DEPT_CD
    , S.CHAGE_ADJ_STTUS_CD
    , S.DESC_SBST
    , S.RQTR_ID
    , S.REVIWR_ID
    , O.BILL_ACC_ID
    , D.PROD_NM
    , C.SVC_CONT_PROD_ID
    , ROWNUM AS RNUM
    FROM BL_BILL_ACC_BILL_TXN A
    JOIN AC_SVC_CONT_BAS B
    ON A.SVC_CONT_ID = B.SVC_CONT_ID
    JOIN MB_CUST_BAS N
    ON B.NFL_CUST_ID = N.CUST_ID 
    JOIN CW_COMN_CD_BAS F
    ON B.BM_CTG_CD = F.CD_ID
    AND CD_GROUP_ID = '70044'
    AND F.EXPNSN_STR_VAL_1 = '01'
    AND F.EFCT_FNS_DT = TO_DATE('99991231', 'YYYYMMDD')
    JOIN AC_SVC_CONT_PROD_DTL C
    ON A.SVC_CONT_ID = C.SVC_CONT_ID
    AND C.LAST_SVC_CONT_PROD_STTUS_CD NOT IN ('C')
    JOIN PR_PROD_BAS D
    ON C.PROD_ID = D.PROD_ID
    AND D.PROD_TYPE_CD = 'P'
    AND D.PROD_EFCT_FNS_DT = TO_DATE('99991231', 'YYYYMMDD')
	 
    LEFT JOIN MB_SALE_PARTY_BAS M
    ON A.SVC_CONT_ID = M.SVC_CONT_ID
    AND SALE_PARTY_DIV_CD = 'S'
    LEFT JOIN MB_CUST_ACC_BAS Q
    ON N.CUST_ID = Q.CUST_ID
    AND Q.ACC_TYPE_CD='1001'
    AND Q.ACC_STTUS_CD='1002' 
    LEFT JOIN (SELECT B.SVC_CONT_ID, B.BILL_TGT_YM, MAX(B.RQTR_ID) AS RQTR_ID, MAX(REVIWR_ID) AS REVIWR_ID, MAX(B.CHAGE_ADJ_STTUS_CD) AS CHAGE_ADJ_STTUS_CD, MAX(B.DESC_SBST) AS DESC_SBST  FROM
                        (SELECT SVC_CONT_ID, BILL_TGT_YM, MAX(STTUS_CHG_DT) as STTUS_CHG_DT FROM BL_CHAGE_ADJ_RQT_TXN
                        WHERE 1=1
               
						   AND BILL_TGT_YM   >=   201801
						 
						 
						   AND BILL_TGT_YM   <=   201812

                        GROUP BY SVC_CONT_ID, BILL_TGT_YM
                        ) A  
                        JOIN BL_CHAGE_ADJ_RQT_TXN B
                        ON A.SVC_CONT_ID = B.SVC_CONT_ID 
                        AND A.BILL_TGT_YM = B.BILL_TGT_YM
                        AND A.STTUS_CHG_DT = B.STTUS_CHG_DT
                        group by B.SVC_CONT_ID, B.BILL_TGT_YM
    ) S
    ON S.SVC_CONT_ID = A.SVC_CONT_ID
    AND S.BILL_TGT_YM = A.BILL_TGT_YM
    LEFT JOIN AC_SVC_CONT_BILL_REL_HST O
    ON A.SVC_CONT_ID = O.SVC_CONT_ID
    AND O.EFCT_FNS_DT = TO_DATE('99991231000000', 'YYYYMMDDHH24MISS')
    WHERE 1=1 
      AND A.BILL_TGT_YM   >=   201801
     
     
       AND A.BILL_TGT_YM   <=   201812
     
    ORDER BY A.BILL_TGT_YM DESC, A.SVC_CONT_ID

    )
    WHERE 1=1
    AND RNUM <= 15 AND RNUM >= 1
) TMP1 
LEFT JOIN (SELECT SVC_CONT_ID, MAX(SVC_CONT_ASSET_1_IDFY_VAL) AS SVC_CONT_ASSET_1_IDFY_VAL FROM AC_SVC_CONT_ASSET_DTL 
WHERE SVC_CONT_ASSET_TYPE_CD = '001' AND SVC_CONT_ASSET_2_IDFY_VAL = '69' 
AND EFCT_FNS_DT = TO_DATE('9999/12/31', 'YYYY/MM/DD') GROUP BY SVC_CONT_ID) E
ON E.SVC_CONT_ID = TMP1.SVC_CONT_ID
LEFT JOIN CW_COMN_CD_BAS G
ON TMP1.LAST_SVC_CONT_STTUS_CD = G.CD_ID
AND G.CD_GROUP_ID = '10253'
AND G.EFCT_FNS_DT = TO_DATE('99991231', 'YYYYMMDD')
LEFT JOIN CW_COMN_CD_BAS I
ON TMP1.CONT_PURP_CD = I.CD_ID
AND I.CD_GROUP_ID = '30001'
LEFT JOIN BL_BILL_WRK_ADM_TXN J
ON TMP1.BILL_TGT_YM = J.BILL_TGT_YM
LEFT JOIN CW_COMN_CD_BAS K
ON J.WRK_STTUS_CD = K.CD_ID
AND K.CD_GROUP_ID = 'WRKSTTUS'
LEFT JOIN CW_COMN_CD_BAS L
ON TMP1.BILL_TRT_RESLT_CD = L.CD_ID
AND L.CD_GROUP_ID = 'TRTRESLTCD'
LEFT JOIN CW_COMN_CD_BAS P
ON TMP1.INET_CIRCUIT_DIV_CD = P.CD_ID
AND P.CD_GROUP_ID = '80001'

LEFT JOIN CW_COMN_CD_BAS T
ON TMP1.CHAGE_ADJ_STTUS_CD =T.CD_ID
AND T.CD_GROUP_ID = 'N000000021'
LEFT JOIN (SELECT SVC_CONT_PROD_ID, COUNT(DC_APLY_ID) AS PRMTN_COUNT FROM AC_DC_APLY_TXN WHERE DC_APLY_TYPE_CD = '01' GROUP BY SVC_CONT_PROD_ID) ADAT
ON TMP1.SVC_CONT_PROD_ID = ADAT.SVC_CONT_PROD_ID

) 