

-- DROP TABLE BATCH_INFO;
CREATE TABLE BATCH_INFO 
(
   JOB_NAME  VARCHAR(100)  NOT NULL ,
   KIND_CD  VARCHAR(10)  NOT NULL ,
   SVR_TYPE_CD  VARCHAR(50)  NOT NULL ,
   JOB_VIEW_NAME  VARCHAR(100)   ,
   CRON_CMD  VARCHAR(100)   ,
   USE_YN  VARCHAR(1)  DEFAULT 'Y' NOT NULL ,
   JOB_INSTANCE_ID  NUMBER(19)   ,
   JOB_KEY  VARCHAR(32)   ,
   VERSION  NUMBER(19)   ,
   JOB_DESC  VARCHAR(200)   
)
 TABLESPACE TS_BIZOWN_COMM_DISK_DATA;
COMMENT ON COLUMN BATCH_INFO.JOB_NAME IS 'JOB_NAME';
COMMENT ON COLUMN BATCH_INFO.JOB_VIEW_NAME IS 'JOB_VIEW_NAME';
COMMENT ON COLUMN BATCH_INFO.KIND_CD IS '종류코드';
COMMENT ON COLUMN BATCH_INFO.CRON_CMD IS '클론명령';
COMMENT ON COLUMN BATCH_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN BATCH_INFO.SVR_TYPE_CD IS '실행대상.서버종류';
COMMENT ON COLUMN BATCH_INFO.JOB_INSTANCE_ID IS 'JOB_INSTANCE_ID';
COMMENT ON COLUMN BATCH_INFO.JOB_KEY IS 'JOB_KEY';
COMMENT ON COLUMN BATCH_INFO.VERSION IS 'VERSION';
COMMENT ON COLUMN BATCH_INFO.JOB_DESC IS '설명';
COMMENT ON TABLE BATCH_INFO IS '배치정보';

GRANT DELETE ON BIZOWN.BATCH_INFO TO BIZAPP;
GRANT INSERT ON BIZOWN.BATCH_INFO TO BIZAPP;
GRANT SELECT ON BIZOWN.BATCH_INFO TO BIZAPP;
GRANT UPDATE ON BIZOWN.BATCH_INFO TO BIZAPP;
GRANT DELETE ON BIZOWN.BATCH_INFO TO BIZBAT;
GRANT INSERT ON BIZOWN.BATCH_INFO TO BIZBAT;
GRANT SELECT ON BIZOWN.BATCH_INFO TO BIZBAT;
GRANT UPDATE ON BIZOWN.BATCH_INFO TO BIZBAT;

ALTER TABLE BATCH_INFO ADD 
 CONSTRAINT BATCH_INFO_PK PRIMARY KEY  ( JOB_NAME,KIND_CD,SVR_TYPE_CD )
 USING INDEX
  TABLESPACE TS_BIZOWN_COMM_DISK_IDX
;



-- DROP TABLE BATCH_INFO_HST;
CREATE TABLE BATCH_INFO_HST 
(
   JOB_NAME  VARCHAR(100)  NOT NULL ,
   CREATE_TIME  DATE NOT NULL ,
   KIND_CD  VARCHAR(10)  NOT NULL ,
   SVR_TYPE_CD  VARCHAR(50)  NOT NULL ,
   JOB_ID  NUMBER(19)  NOT NULL ,
   JOB_EXEC_ID  NUMBER(19)  NOT NULL ,
   START_TIME  DATE  ,
   END_TIME  DATE  ,
   STATUS  VARCHAR(10)   ,
   EXIT_CODE  VARCHAR(2500)   ,
   EXIT_MSG  VARCHAR(4000)   ,
   REST_CNT  NUMBER(9)  DEFAULT 0 NOT NULL  ,
   REST_MSG  VARCHAR(4000)  DEFAULT ''  ,
   LAST_UPDATED  DATE  ,
   PARAMETERS  VARCHAR(200)   
)
 TABLESPACE TS_BIZOWN_COMM_DISK_DATA;
COMMENT ON COLUMN BATCH_INFO_HST.JOB_NAME IS 'JOB_NAME';
COMMENT ON COLUMN BATCH_INFO_HST.CREATE_TIME IS 'JOB생성일시';
COMMENT ON COLUMN BATCH_INFO_HST.KIND_CD IS '종류코드';
COMMENT ON COLUMN BATCH_INFO_HST.SVR_TYPE_CD IS '실행대상.서버종류';
COMMENT ON COLUMN BATCH_INFO_HST.JOB_ID IS 'JOB_INSTANCE_ID';
COMMENT ON COLUMN BATCH_INFO_HST.JOB_EXEC_ID IS 'JOB_EXECUTION_ID';
COMMENT ON COLUMN BATCH_INFO_HST.START_TIME IS '시작일시';
COMMENT ON COLUMN BATCH_INFO_HST.END_TIME IS '종료일시';
COMMENT ON COLUMN BATCH_INFO_HST.STATUS IS '상태';
COMMENT ON COLUMN BATCH_INFO_HST.EXIT_CODE IS '종료코드';
COMMENT ON COLUMN BATCH_INFO_HST.EXIT_MSG IS '종료메시지';
COMMENT ON COLUMN BATCH_INFO_HST.REST_CNT IS '처리개수';
COMMENT ON COLUMN BATCH_INFO_HST.REST_MSG IS '처리내용';
COMMENT ON COLUMN BATCH_INFO_HST.LAST_UPDATED IS '마지막갱신일시';
COMMENT ON COLUMN BATCH_INFO_HST.PARAMETERS IS 'PARAMETERS';
COMMENT ON TABLE BATCH_INFO_HST IS '배치실행정보';

GRANT DELETE ON BIZOWN.BATCH_INFO_HST TO BIZAPP;
GRANT INSERT ON BIZOWN.BATCH_INFO_HST TO BIZAPP;
GRANT SELECT ON BIZOWN.BATCH_INFO_HST TO BIZAPP;
GRANT UPDATE ON BIZOWN.BATCH_INFO_HST TO BIZAPP;
GRANT DELETE ON BIZOWN.BATCH_INFO_HST TO BIZBAT;
GRANT INSERT ON BIZOWN.BATCH_INFO_HST TO BIZBAT;
GRANT SELECT ON BIZOWN.BATCH_INFO_HST TO BIZBAT;
GRANT UPDATE ON BIZOWN.BATCH_INFO_HST TO BIZBAT;

ALTER TABLE BATCH_INFO_HST ADD 
 CONSTRAINT BATCH_INFO_HST_PK PRIMARY KEY  ( JOB_NAME,KIND_CD,SVR_TYPE_CD,CREATE_TIME )
 USING INDEX
  TABLESPACE TS_BIZOWN_COMM_DISK_IDX
;



