SELECT * FROM BATCH_INFO;
SELECT * FROM BATCH_INFO_HST;

-- 권한그룹 종류
SELECT * FROM CW_ATHY_GROUP_BAS;

--SELECT * FROM CW_ATHY_ALC_REL 
--WHERE ATHY_TGT_ID       = '91094035' ;

-- 담당서비스 권한리스트 기준정보 조회 (권한ID:ATHY_ID, 권한명:ATHY_NM, 권한설명:ATHY_DESC_SBST, 권한사용여부:ATHY_USE_YN, 연결메뉴ID:MENU_ID)
SELECT * FROM CW_ATHY_BAS 
    WHERE MENU_ID IN (
        SELECT MENU_ID FROM CW_MENU_BAS WHERE UP_MENU_ID IN (
            SELECT MENU_ID FROM CW_MENU_BAS WHERE MENU_CD = 'PART' -- 담당서비스 기준권한리스트 조회
        )
    )
ORDER BY MENU_ID;


-- 특정ID의 별도권한리스트 조회하기 (20000번 이상, 권한그룹은 50000번 이상)
SELECT E.ATHY_ID
FROM CW_ATHY_ALC_REL A, CW_ATHY_BAS E
WHERE A.ATHY_TGT_ID       = '91094035'
    AND A.ATHY_GROUP_ID = E.MENU_ID
;

-- 특정ID의 별도권한리스트 삭제하기 (20000번 이상, 권한그룹은 50000번 이상)
DELETE FROM CW_ATHY_ALC_REL WHERE ATHY_GROUP_ID < 50000 AND ATHY_TGT_ID = '91094035'
;

-- 특정ID의 별도권한 등록하기 특정사용자의 50000번 미만의 권한그룹을 삭제 후 등록한다. (재등록)
INSERT INTO CW_ATHY_ALC_REL (ATHY_GROUP_ID, ATHY_TGT_ID, FIRST_CRET_TRTR_ID, CRET_DT) SELECT '20101', '91094035', 'admin', CURRENT_TIMESTAMP ;
INSERT INTO CW_ATHY_ALC_REL (ATHY_GROUP_ID, ATHY_TGT_ID, FIRST_CRET_TRTR_ID, CRET_DT) SELECT '20102', '91094035', 'admin', CURRENT_TIMESTAMP ;


-- 특정ID의 전체사용자 권한체크... (메뉴권한 + 별도권한 + 미사용권한) 리스트를 가져온다.
SELECT E.ATHY_ID
FROM mb_user_bas a, CW_ATHY_ALC_REL b,cw_athy_group_bas c,cw_athy_group_athy_rel d, CW_athy_bas e -- ,cw_athy_bas e
WHERE A.USER_ID       = B.ATHY_TGT_ID
  AND B.ATHY_GROUP_ID = C.ATHY_GROUP_ID
  AND C.ATHY_GROUP_ID = D.ATHY_GROUP_ID
  AND D.ATHY_ID       = E.ATHY_ID
  AND C.ATHY_GROUP_STTUS_CD = '01'
  -- AND E.ATHY_STTUS_CD       = '01'
  AND E.ATHY_USE_YN = 'Y'
  AND A.USER_iD       = '91094035'
GROUP BY E.ATHY_ID

UNION

-- 별도권한리스트
SELECT E.ATHY_ID
FROM CW_ATHY_ALC_REL A, CW_ATHY_BAS E
WHERE A.ATHY_TGT_ID       = '91094035'
    AND A.ATHY_GROUP_ID = E.MENU_ID

UNION

SELECT E.ATHY_ID 
FROM
	CW_athy_bas e
WHERE E.ATHY_USE_YN IS NULL
    OR NOT E.ATHY_USE_YN = 'Y' 

;